### ISSUE TITLE
Feature: add_sheets_from_database $table_array_ref

### ISSUE THREAD

**Issue by matthewlenz** [damil/Excel-ValueWriter-XLSX#1]
check for a array ref in @table_names values and allow more advanced but simplistic sql queries.

eg.
```
(
    [tblBasic => [q(select a,b,d,e from tblOne where f = ?), $f]],
    [tblComposite => [q(select t2.*, t3.a, t3.c from tblTwo t2 join tblThree t3 on t2.id = t3.t2_id)]],
    ['tblAll'],  ## gets all data and all columns like normal
    [tblEmpty => 0] ## creates empty sheet with only column names.
)
```

**Comment by matthewlenz** [comment]
I guess you could consider an array of hash refs as well and allow something like:

{ sheet => 'Table One', table => 'tblOne', select => 'select .... = ?', binds => '1' },
{ sheet => 'Table Two', table => 'tblTwo', empty => 1 },
...

This would give better control over things.

**Comment by damil** [comment]
Hi,
Thanks for your suggestion.

The "add_sheets_from_database" method is just a convenience for operations done through "add_sheet()" -- so I don't really want to add more features, because this is not the core business of this module. Besides, SQL generation can take many different forms -- this is why we have so many ORMs and SQL generation modules in CPAN --- I could never have the same level of versatility in ValueWriter.

However, your suggestion makes me think that the add_sheet() method could be improved to make life a bit easier for clients. Currently that method takes either an arrayref of rows, or a coderef to a row generation routine. In addition, it could also take a DBI::st handle, or a DBIx::DataModel statement object. As a result, clients could then generate abritrarily complex SQL requests, using their preferred method, and then just pass the handle to ValueWriter.

I'll publish a new version in the next few days.

Thanks again for the suggestion and for using this module.

Best regards, Laurent

**Comment by matthewlenz** [comment]
Understood! :D  Thanks for the software!  I playing with it quite a bit.  If I have additional ideas/concerns do you want me to open individual issues or just add them here?

**Comment by damil** [comment]
Just add them here

**Comment by damil** [comment]
v1.05 posted to CPAN.
add_sheet(...) can take a $sth argument

**Comment by matthewlenz** [comment]
Thanks! Have you run into any issues with excel (2016 in this case) needing to repair these workbooks?  libreoffice has zero problems with them but not so with excel.  I went so far as to do a selectall_arrayref and then looping through every row and column and striping non-printable characters and it still doesn't seem to help.   It's definately data related as well (it doesn't always happen for different data sets).  Excel (of course) provides no real information about the issue. :(

**Comment by matthewlenz** [comment]
I also found an unrelated issue.  The code checks for duplicate table names (I haven't confirmed if this is case insensitive like it should be)  but I don't believe it does so for column names (or at least not in a case insensitive way).

**Comment by damil** [comment]
> Thanks! Have you run into any issues with excel (2016 in this case) needing to repair these workbooks? libreoffice has zero problems with them but not so with excel. I went so far as to do a selectall_arrayref and then looping through every row and column and striping non-printable characters and it still doesn't seem to help. It's definately data related as well (it doesn't always happen for different data sets). Excel (of course) provides no real information about the issue. :(

What I've seen sometimes is that Excel doesn't like to insert a table with 0 data rows. I forgot this point because my client applications make sure that the dataset is never empty; but this check should really be part of the module.

Otherwise I'm not aware of any other cause. If your data is not confidential you can send me the workbook, I'll try to investigate.

**Comment by damil** [comment]
> I also found an unrelated issue. The code checks for duplicate table names (I haven't confirmed if this is case insensitive like it should be) but I don't believe it does so for column names (or at least not in a case insensitive way).

Excel automatically adds a discriminating number if there are duplicate columns. That's good enough, or clients can check for themselves, so I don't think that the module should reject duplicate columns.
